### ISSUE TITLE
主页加载不了 一直转圈  调用的接口挂了？

### ISSUE THREAD

**Issue by binbin0915** [WangCharlie/douyin#1]
Syncing files to device V1981A...
I/flutter (18664): FormatException: Unexpected character (at character 1)
I/flutter (18664): <!DOCTYPE html>
I/flutter (18664): ^

**Comment by WangCharlie** [comment]
我博客里写了要配合代理..  没有代理加载不出来

**Comment by binbin0915** [comment]
嗯 我挂梯子试试

**Comment by WangCharlie** [comment]
嗯嗯  国际版的需要，不然加载不出数据.
