### ISSUE TITLE
app版本，根本跑不起来啊，一直loading

### ISSUE THREAD

**Issue by WilsonLuck** [WangCharlie/douyin#12]
而且我看之前有人提了，直接被close掉了

**Comment by ShellJor** [comment]
这个是抖音国际版本吧，应该是需要手机翻墙

**Comment by charliewwdev** [comment]
第一个版本国际版需要梯子

**Comment by charliewwdev** [comment]
其他两个抖音国内版不需要

**Comment by charliewwdev** [comment]
刚检查了 是抖音封了接口
![image](https://user-images.githubusercontent.com/6106454/85142310-bcb5b280-b27a-11ea-8058-8dd0953f79e4.png)
