### ISSUE TITLE
如何做到这个播放的时候下一个视频已经预加载完成了

### ISSUE THREAD

**Issue by Hubertzzz** [WangCharlie/douyin#17]

**Comment by Hubertzzz** [comment]
想要实现当前视频播放 下滑下一个已经加载好直接播放 要怎么实现

**Comment by charliewwdev** [comment]
监听视频播放完成

**Comment by ycmmonkey** [comment]
https://pub.dev/packages/preload_page_view 用这个可以，但是播放控制比较费劲调，很不优雅，而且这个库也一直没维护了
