### ISSUE TITLE
跑不起来 报这个错

### ISSUE THREAD

**Issue by songguowei** [WangCharlie/douyin#20]
/E:/flutter/.pub-cache/hosted/pub.flutter-io.cn/getflutter-1.0.11/lib/components/appbar/gf_appbar.dart:311:57: Error: No named parameter with the name 'nullOk'.
    final ScaffoldState scaffold = Scaffold.of(context, nullOk: true);  
                                                        ^^^^^^
/E:/flutter/packages/flutter/lib/src/material/scaffold.dart:1928:24: Context: Found this candidate, but the arguments don't match.
  static ScaffoldState of(BuildContext context) {
                       ^^

FAILURE: Build failed with an exception.

* Where:
Script 'E:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1000

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

**Comment by charliewwdev** [comment]
flutter clean 一下
