### ISSUE TITLE
视频切换过渡的时候，显示错误屏幕

### ISSUE THREAD

**Issue by mjl0602** [WangCharlie/douyin#9]
换播放器可解决这个问题，实际上，我也写了一个仿抖音，解决了这个问题并实现了更多的东西。

具体可以看这里：https://github.com/mjl0602/flutter_tiktok

欢迎学习交流。

**Comment by charliewwdev** [comment]
这个已经修复啦  是因为取值错误，互相学习哈 我也才学几天而已

**Comment by mjl0602** [comment]
你乱划猛滑几下其实还是会有的……我就是一直调不好，最后换播放器了。

抖音的双击点赞我用纯代码写了，你可以直接复制过去用。

效果你可以看博客：https://segmentfault.com/a/1190000021664789?_ea=31447376

**Comment by charliewwdev** [comment]
你拉取最新的代码  已经可以了哦 你这个我看挺好的 可以加进来

**Comment by charliewwdev** [comment]
好的，可以

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: mjl0602<mailto:notifications@github.com>
发送时间: 2020年6月5日 15:59
收件人: WangCharlie/douyin<mailto:douyin@noreply.github.com>
抄送: 乐意分享<mailto:cheng-linw@hotmail.com>; State change<mailto:state_change@noreply.github.com>
主题: Re: [WangCharlie/douyin] 视频切换过渡的时候，显示错误屏幕 (#9)


你乱划猛滑几下其实还是会有的……我就是一直调不好，最后换播放器了。

抖音的双击点赞我用纯代码写了，你可以直接复制过去用。

效果你可以看博客：https://segmentfault.com/a/1190000021664789?_ea=31447376

―
